Style/jasons style branch
FORTRESS-FOR/maneki-interface pull request #10
Opened 2023-04-14 10:43 UTC by jasonkwm

## General Changes

Update Style for Airdrop
Add loading component for Maneki
create component for airdrop content

2023-04-15 00:14 UTC, neosizzle requested changes

2023-04-15 00:14 UTC, neosizzle commented on src/maneki/modules/airdrop/AirdropContentWrapper.tsx
Round up to 2 decimal place for better user experience

2023-04-15 00:16 UTC, neosizzle requested changes
Upon entering invalid address, it is stuck at generating hashes loading

2023-04-16 09:32 UTC, jasonkwm commented
Please check requested change.

2023-04-17 03:03 UTC, neosizzle approved these changes

2023-04-17 03:03 UTC, merged