Style/jasons style branch
FORTRESS-FOR/maneki-interface pull request #13
Opened 2023-05-17 07:31 UTC by jasonkwm

## General Changes & Checklist

- [x] Get PAW balance from smart contract
- [x] Change all number to BigNumberish
- [x] General Styling of Manage Page
- [x] Convert Address to Coin & Link Token To Svg
- [ ] get USD amount for coin through oracle
- [x] QuickAction Panel Add Approval feature
- [ ] Page refresh on wallet change
- [x] Page refresh on success
- [ ] get expired locked paw (backend function empty)
- [x] Improve UI/UX for Success or Error (replace prompt with Modal)
- [x] Dark Theme Compatibility 
- [x] Mobile View
- [x] Translate Manage page 
- [x] Added temporary SVG for PAW Coin icon

## Developer Notes

Add any notes here that may be helpful for reviewers.

2023-05-18 02:17 UTC, neosizzle requested changes

2023-05-18 02:17 UTC, neosizzle commented on src/ui-config/marketsConfig.tsx
Looks like you are hardcoding the address for this variable, Ill send you the address soon so you can add it to your .env

2023-05-18 02:17 UTC, neosizzle commented on src/locales/en/messages.js
Locales not functioning in build,
![image](https://github.com/FORTRESS-FOR/maneki-interface/assets/44501267/abaa7396-78c7-4e11-b756-c8a6d0ff15db)

2023-05-18 02:17 UTC, neosizzle commented on src/locales/en/messages.js
This can be fixed by rebuilding with different i18n parameters, can be tested by building and serving locally.

2023-05-18 03:27 UTC, jasonkwm commented on src/locales/en/messages.js
i think its alright now. :D

2023-05-18 03:59 UTC, jasonkwm commented
Ok i hope the problem is fix. please review again. :D

2023-05-22 01:44 UTC, neosizzle requested changes
![image](https://github.com/FORTRESS-FOR/maneki-interface/assets/44501267/d974eeb8-7d8e-4e47-94bd-636c86857d20)
Manage Paw right panel infinite loading, I think its something to do with this error :


![image](https://github.com/FORTRESS-FOR/maneki-interface/assets/44501267/d8408a1d-bc5f-4fc9-84b6-f56cafc06749)


Where you called a smart contract without declaring a signer. Everything else is OK for me.

2023-05-22 04:19 UTC, neosizzle commented
The above error turns out to be a misconfiguration in vercel, it is already rectified on that side.

2023-05-22 04:19 UTC, neosizzle approved these changes

2023-05-22 04:19 UTC, merged