Feat/core logic preparation
FORTRESS-FOR/maneki-interface pull request #40
Opened 2023-08-01 09:52 UTC by jasonkwm

## General Changes

- Core logic clean up
- Swap to arbitrum from bsc testnet
- Added Leverage feature

2023-08-02 02:03 UTC, neosizzle commented on src/maneki/modules/markets/ClaimRewardTopPanel.tsx
REWARD_TOKEN_ADDR should be in env var

2023-08-02 02:13 UTC, neosizzle commented on src/components/lists/ListMobileItem.tsx
<img width="305" alt="Screenshot 2023-08-02 at 10 12 50" src="https://github.com/FORTRESS-FOR/maneki-interface/assets/44501267/ba04a704-d77e-4fdf-999a-2075f0c88e9a">
clipping of percentage values in desktop

2023-08-02 02:15 UTC, neosizzle commented on src/modules/markets/MarketAssetsListItem.tsx
<img width="305" alt="Screenshot 2023-08-02 at 10 12 50" src="https://github.com/FORTRESS-FOR/maneki-interface/assets/44501267/c1955436-75dd-41ba-9a55-f65142bb6e71">

Clipping with the 2x to 10x values

2023-08-02 02:17 UTC, neosizzle commented on src/uiConfig.ts
Where is the replacement for the logo?

2023-08-02 02:18 UTC, neosizzle requested changes
Changes needed on styling of the glp menu item and some env var abstractions

2023-08-02 03:12 UTC, jasonkwm commented on src/uiConfig.ts
Using a different method to get logo.

2023-08-02 03:12 UTC, jasonkwm commented on src/modules/markets/MarketAssetsListItem.tsx
added min width to prevent clipping

2023-08-02 03:12 UTC, jasonkwm commented on src/maneki/modules/markets/ClaimRewardTopPanel.tsx
done

2023-08-04 01:48 UTC, neosizzle approved these changes

2023-08-04 01:54 UTC, merged